Server sheep
bolt-rip/lobby pull request #2
Opened 2021-02-11 16:24 UTC by dentmaged

2021-02-11 20:31 UTC, Pablete1234 requested changes

2021-02-11 20:31 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/utils/Bungee.java
> +  public static void getPlayerCount(ServerStatus server) {
calling a method `get*` when the result is void is insulting.

2021-02-13 18:56 UTC, Pugzy commented on src/main/java/rip/bolt/lobby/api/APIManager.java
> +  public ObjectMapper getObjectMapper() {
Created and passed to both objects, not sure where or how it could be put somewhere else.

2021-02-13 18:56 UTC, Pugzy commented on src/main/java/rip/bolt/lobby/manager/servers/NPCLocator.java
> +    ordered.forEach(location -> statues.add(new ServerSlot(location)));
Switched to ordering system using indexes rather than mutating arrays.

2021-02-13 20:07 UTC, Pablete1234 requested changes

2021-02-13 20:07 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/manager/servers/PlayerCountUpdater.java
> +            .collect(Collectors.toList());
i've seen this stream other times, move it to the locator, add a `getLocator().getServers()` that returns the stream:

```
        return getSlots().stream()
            .map(slot -> slot.getServerStatus().orElse(null))
            .filter(Objects::nonNull);
```

2021-02-13 20:07 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/redis/RedisManager.java
> +    }
If redis is disabled, we simply don't send messages, why would we receive the same that we sent? seems a rather silly no-op implementation

2021-02-13 20:07 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/redis/RedisManager.java
> +      return false;
include `e.printStackTrace();`

2021-02-13 20:07 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/utils/NMSHacks.java
> +    // tag.setBoolean("Invulnerable", true);
Should this be here or not?

2021-02-13 20:50 UTC, Pugzy commented on src/main/java/rip/bolt/lobby/config/Config.java
> +          (float) config.getDouble("center.yaw", 90); // getFloat returns the default every time
@dentmaged did you try this one? Not sure if you mentioned it.

2021-02-13 23:26 UTC, Pugzy commented on src/main/java/rip/bolt/lobby/commands/NPCCommand.java
> +    BoltLobby.getInstance().getNpcManager().clear();
This doesn't seem too essential. Ingame does it this way too.

2021-02-14 07:26 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/commands/NPCCommand.java
> +    BoltLobby.getInstance().getNpcManager().clear();
it's not the biggest one, but it'd still be nice

2021-02-14 07:26 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/redis/RedisManager.java
> +    }
```suggestion
    if (!redisConfig.isEnabled()) return;
    Jedis jedis = pool.getResource();
    try {
      jedis.publish(channel, message);
    } finally {
      jedis.close();
    }
```

2021-02-14 17:51 UTC, Pablete1234 requested changes

2021-02-14 17:51 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/manager/NPCManager.java
> +                return;
```suggestion
              if (!player.isOnline() || !ViaUtils.isLegacy(player)) return;
```

Just simplify it, make isLegacy return false if viautils isn't enabled

2021-02-14 17:51 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/manager/servers/ServerStatus.java
> +    System.out.println(serverName + " assigned id: " + fakeEntityId);
```suggestion
```

2021-02-14 17:51 UTC, Pablete1234 commented on src/main/java/rip/bolt/lobby/utils/NMSHacks.java
> +  }
A bit of duplicate code between these 2

Make one method that freezes for one player (the one below is just fine) and make the one above just call it for each player

2021-02-14 19:08 UTC, Pablete1234 approved these changes

2021-02-14 19:08 UTC, merged